name       : d-spy
version    : 1.6.0
release    : 3
source     :
    - https://download.gnome.org/sources/d-spy/1.6/d-spy-1.6.0.tar.xz : a2d0a210513bb46470d00e34544791208330153f4cb34f8587172911ac4f8afd
license    : GPL-3.0-or-later
component  : system.utils
summary    : System D-BUS viewer
description: |
    System D-BUS viewer. It's like d-feet, but written in C and blisteringly fast. Also comes with a library for IDE integration.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
