name       : d-spy
version    : 1.4.0
release    : 2
source     :
    - https://download.gnome.org/sources/d-spy/1.4/d-spy-1.4.0.tar.xz : eae8748cea624c5c4c75e021c2df1d7376e4f9f8fbe89ac4434911ecf7886772
license    : GPL-3.0-or-later
component  : system.utils
summary    : System D-BUS viewer
description: |
    System D-BUS viewer. It's like d-feet, but written in C and blisteringly fast. Also comes with a library for IDE integration.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
